
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertWeights", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/ConvertWeight.asmx?WSDL")
public class ConvertWeights
    extends Service
{

    private final static URL CONVERTWEIGHTS_WSDL_LOCATION;
    private final static WebServiceException CONVERTWEIGHTS_EXCEPTION;
    private final static QName CONVERTWEIGHTS_QNAME = new QName("http://www.webserviceX.NET/", "ConvertWeights");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/ConvertWeight.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTWEIGHTS_WSDL_LOCATION = url;
        CONVERTWEIGHTS_EXCEPTION = e;
    }

    public ConvertWeights() {
        super(__getWsdlLocation(), CONVERTWEIGHTS_QNAME);
    }

    public ConvertWeights(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTWEIGHTS_QNAME, features);
    }

    public ConvertWeights(URL wsdlLocation) {
        super(wsdlLocation, CONVERTWEIGHTS_QNAME);
    }

    public ConvertWeights(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTWEIGHTS_QNAME, features);
    }

    public ConvertWeights(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertWeights(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConvertWeightsSoap
     */
    @WebEndpoint(name = "ConvertWeightsSoap")
    public ConvertWeightsSoap getConvertWeightsSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "ConvertWeightsSoap"), ConvertWeightsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertWeightsSoap
     */
    @WebEndpoint(name = "ConvertWeightsSoap")
    public ConvertWeightsSoap getConvertWeightsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "ConvertWeightsSoap"), ConvertWeightsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTWEIGHTS_EXCEPTION!= null) {
            throw CONVERTWEIGHTS_EXCEPTION;
        }
        return CONVERTWEIGHTS_WSDL_LOCATION;
    }

}
